#!/bin/bash
lein cljsbuild once release
cp resources/public/index_release.html ~/jborden/ld38_postjam/index.html
cp resources/public/js/greedy_pigeon.min.js ~/jborden/ld38_postjam/js/
cp -r resources/public/images ~/jborden/ld38_postjam
cp -r resources/public/css ~/jborden/ld38_postjam
cp -r resources/public/fonts ~/jborden/ld38_postjam
cp -r resources/public/audio ~/jborden/ld38_postjam
